import type { Dict } from "./de";

export const en: Dict = {
  meta: {
    title: "GuestTap | NFC + QR review cards for hotels in Mannheim",
    description:
      "More genuine Google reviews, one tap away. NFC review plates and NFC + QR countertop stands for independent hotels, guesthouses and boarding houses. Preconfigured, no app, no subscription.",
  },
  skip: "Skip to content",
  nav: {
    links: [
      { href: "#produkt", label: "Product" },
      { href: "#so-gehts", label: "How it works" },
      { href: "#fuer-hotels", label: "For hotels" },
      { href: "#preise", label: "Pricing" },
      { href: "#faq", label: "FAQ" },
      { href: "#kontakt", label: "Contact" },
    ],
    cta: "See samples",
    menu: "Menu",
    close: "Close",
    langLabel: "Choose language",
  },
  hero: {
    eyebrow: "NFC + QR review cards for hotels",
    line1: "More genuine Google reviews.",
    line2a: "One",
    line2b: "tap",
    sub: "Make it as easy as possible for your guests to share their experience. Hold the phone close or scan the QR code. Done.",
    cta1: "See samples",
    cta2: "Request for my hotel",
    chips: ["No app", "No subscription", "Preconfigured"],
    note: "Handmade in Mannheim. By two people, after hours.",
  },
  mock: {
    alt: "Black GuestTap countertop stand with QR code and adhesive plate “We would appreciate your Google review!” with NFC symbol",
    toggle: "Design language",
  },
  problem: {
    eyebrow: "The problem",
    title: "Happy guests rarely review on their own.",
    cards: [
      { time: "11:02", title: "The guest is happy", text: "The stay was great and the guest leaves satisfied." },
      { time: "11:40", title: "The review gets forgotten", text: "Later, they would first have to look up your hotel on Google." },
      { time: "21:15", title: "A good stay stays invisible", text: "A happy guest never turns into a public review." },
    ],
    turnA: "GuestTap removes exactly this",
    turnB: "hurdle",
    turnSub: "The review happens while the guest is still there. With the phone that's already in their hand.",
  },
  how: {
    eyebrow: "How it works",
    title: "This is how simple GuestTap is",
    hint: "Tap a key",
    steps: [
      { title: "We set up your plate", text: "Send us the link to your Google Business profile. Or just the name of your place. We set it all up, test and ship." },
      { title: "Place it or stick it", text: "At reception, in the breakfast room, at checkout, in the lobby or right by the exit." },
      { title: "Guest taps or scans", text: "Hold the phone to the plate. The countertop stand also has a QR code. No app, no sign-up." },
      { title: "Google opens right away", text: "Your review page opens instantly. The guest freely decides whether and what to write." },
    ],
    phone: {
      linked: "Link connected",
      linkedSub: "Your Google profile",
      tested: "Tested on iOS + Android",
      placed: "Reception",
      placedSub: "Standing. Sticking. Waiting.",
      reading: "Plate detected",
      readingSub: "Opening …",
      reviewTitle: "Write a review",
      reviewPlace: "Your hotel",
      reviewPh: "Share details of your experience",
      post: "Post",
    },
  },
  products: {
    eyebrow: "Product",
    title: "This is what our plates look like.",
    sub: "Exactly these designs, nothing else. In German or English, just switch.",
    perPiece: "per piece",
    cta: "Request a sample",
    items: [
      { name: "Review plate", tag: "Adhesive", price: "€40", features: ["NFC chip: hold the phone close, done", "Sticks to counters, tables, glass or walls", "Design in German or English", "Preconfigured with your Google link"] },
      { name: "Countertop stand", tag: "For reception and buffet", price: "€60", features: ["NFC + QR code", "Black acrylic, premium finish", "Design in German or English", "Preconfigured with your Google link"] },
    ],
    volume: "Need several? There's a volume discount.",
    volumeSub: "For multiple plates or stands we're happy to give you a better price. Just tell us how many you need.",
    volumeCta: "Ask for a volume discount",
    service: {
      badge: "Optional",
      name: "Google optimisation",
      tag: "Your profile, properly tidied up",
      text: "If you like, we'll also polish your Google Business profile. So guests who find you actually want to book.",
      features: ["Fresh photos and a good description", "Right categories, hours and amenities", "Tips for replying to reviews", "No ranking promises, just honest work"],
      price: "on request",
      cta: "Ask about optimisation",
      mockName: "Your hotel",
      mockType: "Hotel in Mannheim",
      mockTabs: ["Overview", "Reviews", "Photos"],
    },
  },
  delivery: {
    title: "Arrives ready to go.",
    text: "Set up, tested and neatly packed. Around Mannheim / Rhein-Neckar we're happy to drop it off in person.",
    alt: "GuestTap review plates and countertop stands in a shipping box at a hotel reception",
  },
  howPhoto: { alt: "Guest reviewing a hotel in seconds via NFC on the GuestTap plate" },
  uses: {
    eyebrow: "For hotels",
    title: "Right where the guest wraps up their stay.",
    sub: "Guesthouses, boarding houses, family hotels. Anywhere people love to come back to.",
    spots: [
      { key: "reception", img: "/images/rezeption.jpg", product: "Review plate", title: "Reception / checkout", text: "Key handed back, phone in hand, everything still fresh. The best moment.", alt: "Guest scanning the GuestTap review plate at the hotel reception" },
      { key: "breakfast", img: "/images/fruehstueck.jpg", product: "Countertop stand", title: "Breakfast room", text: "Second coffee, plenty of time. The stand fits on any table.", alt: "Black GuestTap countertop stand on a breakfast table" },
      { key: "nightstand", img: "/images/nachttisch.jpg", product: "Review plate", title: "Nightstand", text: "One last look at the phone before sleep? That's the moment.", alt: "GuestTap review plate on the nightstand in a hotel room" },
      { key: "desk", img: "/images/schreibtisch.jpg", product: "Review plate", title: "Desk in the room", text: "Discreetly on the edge of the desk. Always there, never in the way.", alt: "Guest scanning the GuestTap review plate on the room desk" },
    ],
  },
  rules: {
    eyebrow: "Fair play",
    title: "House rules",
    sub: "A few rules we don't negotiate.",
    items: [
      { title: "Genuine reviews only.", text: "We make it easier to leave a review. What it says is entirely up to the guest." },
      { title: "No incentives.", text: "No discount and no free drink for stars. Google's policies forbid it, and it just feels wrong." },
      { title: "No review gating.", text: "Every guest lands on the same page. We never filter anyone out beforehand." },
      { title: "Not Google.", text: "GuestTap is an independent company. We are not affiliated with or endorsed by Google." },
    ],
  },
  pricing: {
    eyebrow: "Pricing",
    title: "Pay once. That's it.",
    sub: "No term, no licence, no fine print. You buy the plate, you own it.",
    folio: "Invoice",
    folioNo: "No. 0001",
    guest: "Guest: your hotel",
    lines: [
      { label: "Review plate", value: "€40" },
      { label: "Countertop stand", value: "€60" },
      { label: "Several pieces", value: "Volume discount", divider: true },
      { label: "Google link setup", value: "€0", free: true },
      { label: "Monthly subscription", value: "€0", free: true },
      { label: "App for guests", value: "€0", free: true },
      { label: "Google optimisation", value: "optional", divider: true },
    ],
    footnote: "Minibar not included.",
    small: "Prices per piece, plus shipping. Around Mannheim / Rhein-Neckar we're happy to drop by in person.",
    cta: "Get a quote for my place",
  },
  team: {
    eyebrow: "Who's behind it",
    title: "We're a team of two. On purpose.",
    body: [
      "We run GuestTap as a side business from Mannheim. By day we have regular jobs. In the evenings we set up plates, test every single one on several phones and sometimes drive samples over ourselves.",
      "For you that means no ticket system, no hold music, no sales rep with a headset. You write to us, we reply. Usually the same evening.",
    ],
    facts: [
      { k: "2", v: "people" },
      { k: "0", v: "call centres" },
      { k: "MA", v: "Rhein-Neckar" },
    ],
    photo: "Team photo coming soon",
    photoAlt: "The GuestTap team in a hotel corridor with a review plate and phone",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions we hear a lot.",
    items: [
      { q: "Do my guests need an app?", a: "No. Current iPhones and most Android phones read NFC natively. The countertop stand also has a QR code for anyone who prefers scanning with the camera." },
      { q: "Are there any ongoing costs?", a: "No. You pay once for plates and stands. No subscription, no licence, no surprise on the next invoice. Google optimisation is optional and agreed separately." },
      { q: "What exactly do you set up?", a: "We connect the NFC chip (and on the stand the QR code) to the direct review link of your Google Business profile. Send us the link, or just the name of your place, and we'll find the rest." },
      { q: "Is this in line with Google's policies?", a: "As long as it stays fair, yes. The card asks every guest the same way, with no reward and no pre-filtering. That's exactly how we built it." },
      { q: "Is there a volume discount?", a: "Yes. For several plates or stands we're happy to give you a better price. Just tell us how many you need." },
      { q: "Are the plates available in English?", a: "Yes. Plate and stand come in German or English. Switch the design in the product section to see exactly how it looks." },
      { q: "What does the Google optimisation include?", a: "If you want, we take care of your Google Business profile: fresh photos, a good description, the right categories, hours and amenities, plus tips for replying to reviews. We don't promise rankings, but your profile will be complete and inviting." },
      { q: "Can we see a sample first?", a: "Sure. Around Mannheim / Rhein-Neckar we're happy to bring samples by. Otherwise we'll send photos and a short video." },
      { q: "What if our Google profile changes?", a: "Just let us know. We'll look into it and find a solution without you having to buy everything again." },
      { q: "Are you Google?", a: "No. GuestTap is an independent company and not affiliated with Google. We just help guests find your review page faster." },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Ring the bell.",
    sub: "Samples, questions, pricing for several properties. Drop us a line and we'll get back to you personally.",
    bell: "Ring the bell",
    mailLabel: "Or email us directly",
    region: "Mannheim / Rhein-Neckar",
    form: {
      hotel: "Hotel or property",
      name: "Your name",
      email: "Email",
      interest: "What are you interested in?",
      interests: ["See samples", "Review plate", "Countertop stand", "Volume discount", "Google optimisation", "Just a chat"],
      message: "Message (optional)",
      messagePh: "How many plates or stands, German or English …",
      submit: "Send request by email",
      note: "Opens your email app with a ready-made message to us. No newsletter, promise.",
      subject: "GuestTap enquiry",
      required: "Required",
    },
  },
  footer: {
    claim: "More genuine reviews. One tap away.",
    legal: "GuestTap is an independent company and is not affiliated with or endorsed by Google LLC. Google is a trademark of Google LLC.",
    imprint: "Legal notice",
    privacy: "Privacy",
    made: "Made in Mannheim",
  },
};
